version: '3'
services:
  minio1:
    image: minio/minio:latest
    restart: always
    container_name: cluster_minio_1
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /minio/data/1:/minio:rw
      - /minio/config/1:/root/.minio:rw
    command: server http://minio{1...4}/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      - minio_net

  minio2:
    image: minio/minio:latest
    restart: always
    container_name: cluster_minio_2
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /minio/data/2:/minio:rw
      - /minio/config/2:/root/.minio:rw
    command: server http://minio{1...4}/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net

  minio3:
    image: minio/minio:latest
    restart: always
    container_name: cluster_minio_3
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /minio/data/3:/minio:rw
      - /minio/config/3:/root/.minio:rw
    command: server http://minio{1...4}/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net

  minio4:
    image: minio/minio:latest
    restart: always
    container_name: cluster_minio_4
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /minio/data/4:/minio:rw
      - /minio/config/4:/root/.minio:rw
    command: server http://minio{1...4}/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net

  minio:
    image: minio/minio:latest
    restart: always
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
    command: server http://minio{1...4}/minio
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge
